# build from the official Nginx image
FROM nginx

MAINTAINER Silvia Puglisi <silvia@nopressure.go.uk>

WORKDIR /$APPROOT
ENV APPROOT api

# install essential Linux packages
RUN apt-get update -qq && apt-get -y install apache2-utils

# establish where Nginx should look for files
ENV RAILS_ROOT /api

# Set our working directory inside the image
WORKDIR $RAILS_ROOT

# create log directory
RUN mkdir log

# copy our Nginx config template
COPY /config/nginx.conf /tmp/api.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst $RAILS_ROOT < /tmp/api.nginx > /etc/nginx/conf.d/default.conf

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]
